"""
SwissBuildingOS - Remediation Cost Reference Seed
Idempotent seed script with Swiss market averages (2024-2025).

Usage:
    python -m app.seeds.seed_cost_references
"""

import asyncio
import uuid

from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models.remediation_cost_reference import RemediationCostReference

# ---------------------------------------------------------------------------
# Stable UUIDs for idempotent upserts (UUID5 namespace)
# ---------------------------------------------------------------------------
_NS = uuid.UUID("c0500000-0000-4000-a000-000000000001")

COST_REFERENCES = [
    # ── Asbestos ──────────────────────────────────────────────────────
    {
        "id": uuid.uuid5(_NS, "asbestos-flocage-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "flocage",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 150,
        "cost_per_m2_median": 250,
        "cost_per_m2_max": 350,
        "is_forfait": False,
        "duration_days_estimate": 30,
        "complexity": "complexe",
        "description": "Dépose de flocage amianté — intervention lourde, confinement requis",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-dalle_vinyle-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "dalle_vinyle",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 50,
        "cost_per_m2_median": 85,
        "cost_per_m2_max": 120,
        "is_forfait": False,
        "duration_days_estimate": 10,
        "complexity": "moyenne",
        "description": "Dépose de dalles vinyle amiantées — retrait mécanique",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-joint-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "joint",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 80,
        "cost_per_m2_median": 140,
        "cost_per_m2_max": 200,
        "is_forfait": False,
        "duration_days_estimate": 7,
        "complexity": "moyenne",
        "description": "Dépose de joints amiantés — fenêtres, sanitaire, façade",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-colle-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "colle",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 60,
        "cost_per_m2_median": 100,
        "cost_per_m2_max": 150,
        "is_forfait": False,
        "duration_days_estimate": 10,
        "complexity": "moyenne",
        "description": "Dépose de colle amiantée — carrelage, revêtement de sol",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-isolation-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "isolation",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 100,
        "cost_per_m2_median": 175,
        "cost_per_m2_max": 250,
        "is_forfait": False,
        "duration_days_estimate": 22,
        "complexity": "complexe",
        "description": "Dépose d'isolation amiantée — calorifuge, gaine technique",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-enduit-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "enduit",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 70,
        "cost_per_m2_median": 130,
        "cost_per_m2_max": 190,
        "is_forfait": False,
        "duration_days_estimate": 12,
        "complexity": "moyenne",
        "description": "Dépose d'enduit amianté — crépis, plâtre intérieur",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-revetement-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "revetement",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 55,
        "cost_per_m2_median": 90,
        "cost_per_m2_max": 130,
        "is_forfait": False,
        "duration_days_estimate": 8,
        "complexity": "moyenne",
        "description": "Dépose de revêtement de sol amianté — linoleum, moquette",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-conduit-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "conduit",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 120,
        "cost_per_m2_median": 200,
        "cost_per_m2_max": 280,
        "is_forfait": False,
        "duration_days_estimate": 18,
        "complexity": "complexe",
        "description": "Dépose de conduits/gaines fibro-ciment amiantés",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-toiture-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "toiture",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 40,
        "cost_per_m2_median": 70,
        "cost_per_m2_max": 100,
        "is_forfait": False,
        "duration_days_estimate": 14,
        "complexity": "moyenne",
        "description": "Dépose de plaques fibro-ciment en toiture",
    },
    {
        "id": uuid.uuid5(_NS, "asbestos-other-degrade-depose"),
        "pollutant_type": "asbestos",
        "material_type": "other",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 80,
        "cost_per_m2_median": 150,
        "cost_per_m2_max": 220,
        "is_forfait": False,
        "duration_days_estimate": 15,
        "complexity": "moyenne",
        "description": "Dépose générique amiante — matériau non classifié",
    },
    # ── PCB ───────────────────────────────────────────────────────────
    {
        "id": uuid.uuid5(_NS, "pcb-joint-degrade-depose"),
        "pollutant_type": "pcb",
        "material_type": "joint",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 100,
        "cost_per_m2_median": 175,
        "cost_per_m2_max": 250,
        "is_forfait": False,
        "duration_days_estimate": 15,
        "complexity": "moyenne",
        "description": "Dépose de joints PCB — élastiques de façade, fenêtres",
    },
    {
        "id": uuid.uuid5(_NS, "pcb-peinture-degrade-decapage"),
        "pollutant_type": "pcb",
        "material_type": "peinture",
        "condition": "degrade",
        "method": "decapage",
        "cost_per_m2_min": 80,
        "cost_per_m2_median": 130,
        "cost_per_m2_max": 180,
        "is_forfait": False,
        "duration_days_estimate": 12,
        "complexity": "moyenne",
        "description": "Décapage de peinture contenant des PCB",
    },
    {
        "id": uuid.uuid5(_NS, "pcb-revetement-degrade-depose"),
        "pollutant_type": "pcb",
        "material_type": "revetement",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 90,
        "cost_per_m2_median": 150,
        "cost_per_m2_max": 210,
        "is_forfait": False,
        "duration_days_estimate": 14,
        "complexity": "moyenne",
        "description": "Dépose de revêtement contenant des PCB — sols, murs",
    },
    {
        "id": uuid.uuid5(_NS, "pcb-enduit-degrade-decapage"),
        "pollutant_type": "pcb",
        "material_type": "enduit",
        "condition": "degrade",
        "method": "decapage",
        "cost_per_m2_min": 85,
        "cost_per_m2_median": 140,
        "cost_per_m2_max": 195,
        "is_forfait": False,
        "duration_days_estimate": 10,
        "complexity": "moyenne",
        "description": "Décapage d'enduit contenant des PCB",
    },
    {
        "id": uuid.uuid5(_NS, "pcb-other-degrade-depose"),
        "pollutant_type": "pcb",
        "material_type": "other",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 95,
        "cost_per_m2_median": 160,
        "cost_per_m2_max": 225,
        "is_forfait": False,
        "duration_days_estimate": 13,
        "complexity": "moyenne",
        "description": "Assainissement PCB — matériau non classifié",
    },
    # ── Lead ──────────────────────────────────────────────────────────
    {
        "id": uuid.uuid5(_NS, "lead-peinture-degrade-decapage"),
        "pollutant_type": "lead",
        "material_type": "peinture",
        "condition": "degrade",
        "method": "decapage",
        "cost_per_m2_min": 60,
        "cost_per_m2_median": 105,
        "cost_per_m2_max": 150,
        "is_forfait": False,
        "duration_days_estimate": 7,
        "complexity": "simple",
        "description": "Décapage de peinture au plomb — surfaces intérieures",
    },
    {
        "id": uuid.uuid5(_NS, "lead-enduit-degrade-depose"),
        "pollutant_type": "lead",
        "material_type": "enduit",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 70,
        "cost_per_m2_median": 120,
        "cost_per_m2_max": 170,
        "is_forfait": False,
        "duration_days_estimate": 12,
        "complexity": "moyenne",
        "description": "Dépose d'enduit contenant du plomb",
    },
    {
        "id": uuid.uuid5(_NS, "lead-conduit-degrade-depose"),
        "pollutant_type": "lead",
        "material_type": "conduit",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 90,
        "cost_per_m2_median": 155,
        "cost_per_m2_max": 220,
        "is_forfait": False,
        "duration_days_estimate": 10,
        "complexity": "moyenne",
        "description": "Remplacement de conduites en plomb — eau potable",
    },
    {
        "id": uuid.uuid5(_NS, "lead-other-degrade-decapage"),
        "pollutant_type": "lead",
        "material_type": "other",
        "condition": "degrade",
        "method": "decapage",
        "cost_per_m2_min": 65,
        "cost_per_m2_median": 110,
        "cost_per_m2_max": 160,
        "is_forfait": False,
        "duration_days_estimate": 8,
        "complexity": "simple",
        "description": "Assainissement plomb — matériau non classifié",
    },
    {
        "id": uuid.uuid5(_NS, "lead-revetement-degrade-depose"),
        "pollutant_type": "lead",
        "material_type": "revetement",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 55,
        "cost_per_m2_median": 95,
        "cost_per_m2_max": 140,
        "is_forfait": False,
        "duration_days_estimate": 9,
        "complexity": "simple",
        "description": "Dépose de revêtement contenant du plomb — peinture murale, sol",
    },
    # ── HAP ───────────────────────────────────────────────────────────
    {
        "id": uuid.uuid5(_NS, "hap-revetement-degrade-depose"),
        "pollutant_type": "hap",
        "material_type": "revetement",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 80,
        "cost_per_m2_median": 140,
        "cost_per_m2_max": 200,
        "is_forfait": False,
        "duration_days_estimate": 15,
        "complexity": "moyenne",
        "description": "Dépose de revêtement contenant des HAP — étanchéité, bitume",
    },
    {
        "id": uuid.uuid5(_NS, "hap-toiture-degrade-depose"),
        "pollutant_type": "hap",
        "material_type": "toiture",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 60,
        "cost_per_m2_median": 110,
        "cost_per_m2_max": 160,
        "is_forfait": False,
        "duration_days_estimate": 12,
        "complexity": "moyenne",
        "description": "Dépose de couverture bitumineuse HAP — toiture plate",
    },
    {
        "id": uuid.uuid5(_NS, "hap-isolation-degrade-depose"),
        "pollutant_type": "hap",
        "material_type": "isolation",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 75,
        "cost_per_m2_median": 130,
        "cost_per_m2_max": 185,
        "is_forfait": False,
        "duration_days_estimate": 14,
        "complexity": "moyenne",
        "description": "Dépose d'isolation contenant des HAP — liège bitumé",
    },
    {
        "id": uuid.uuid5(_NS, "hap-colle-degrade-depose"),
        "pollutant_type": "hap",
        "material_type": "colle",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 65,
        "cost_per_m2_median": 115,
        "cost_per_m2_max": 165,
        "is_forfait": False,
        "duration_days_estimate": 10,
        "complexity": "moyenne",
        "description": "Dépose de colle noire contenant des HAP — parquet, carrelage",
    },
    {
        "id": uuid.uuid5(_NS, "hap-other-degrade-depose"),
        "pollutant_type": "hap",
        "material_type": "other",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 70,
        "cost_per_m2_median": 125,
        "cost_per_m2_max": 180,
        "is_forfait": False,
        "duration_days_estimate": 13,
        "complexity": "moyenne",
        "description": "Assainissement HAP — matériau non classifié",
    },
    # ── Radon ─────────────────────────────────────────────────────────
    {
        "id": uuid.uuid5(_NS, "radon-other-bon-ventilation"),
        "pollutant_type": "radon",
        "material_type": "other",
        "condition": "bon",
        "method": "ventilation",
        "cost_per_m2_min": None,
        "cost_per_m2_median": None,
        "cost_per_m2_max": None,
        "is_forfait": True,
        "forfait_min": 5000,
        "forfait_median": 10000,
        "forfait_max": 15000,
        "duration_days_estimate": 5,
        "complexity": "simple",
        "description": "Installation d'un système de ventilation anti-radon — forfait par bâtiment",
    },
    {
        "id": uuid.uuid5(_NS, "radon-other-degrade-confinement"),
        "pollutant_type": "radon",
        "material_type": "other",
        "condition": "degrade",
        "method": "confinement",
        "cost_per_m2_min": None,
        "cost_per_m2_median": None,
        "cost_per_m2_max": None,
        "is_forfait": True,
        "forfait_min": 8000,
        "forfait_median": 15000,
        "forfait_max": 25000,
        "duration_days_estimate": 10,
        "complexity": "moyenne",
        "description": "Étanchéification dalle + ventilation — cas de concentration élevée",
    },
    # ── PFAS ──────────────────────────────────────────────────────────
    {
        "id": uuid.uuid5(_NS, "pfas-other-degrade-depose"),
        "pollutant_type": "pfas",
        "material_type": "other",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 100,
        "cost_per_m2_median": 200,
        "cost_per_m2_max": 300,
        "is_forfait": False,
        "duration_days_estimate": 22,
        "complexity": "complexe",
        "description": "Assainissement PFAS — protocole émergent, coûts variables",
    },
    {
        "id": uuid.uuid5(_NS, "pfas-revetement-degrade-depose"),
        "pollutant_type": "pfas",
        "material_type": "revetement",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 120,
        "cost_per_m2_median": 220,
        "cost_per_m2_max": 320,
        "is_forfait": False,
        "duration_days_estimate": 20,
        "complexity": "complexe",
        "description": "Dépose de revêtement contaminé PFAS — sol industriel",
    },
    {
        "id": uuid.uuid5(_NS, "pfas-isolation-degrade-depose"),
        "pollutant_type": "pfas",
        "material_type": "isolation",
        "condition": "degrade",
        "method": "depose",
        "cost_per_m2_min": 110,
        "cost_per_m2_median": 210,
        "cost_per_m2_max": 310,
        "is_forfait": False,
        "duration_days_estimate": 18,
        "complexity": "complexe",
        "description": "Dépose d'isolation contaminée PFAS — mousse, panneau",
    },
]


async def seed_cost_references():
    """Idempotent seed: insert or skip remediation cost references."""
    async with AsyncSessionLocal() as session:
        for ref_data in COST_REFERENCES:
            ref_id = ref_data["id"]
            existing = await session.execute(
                select(RemediationCostReference).where(RemediationCostReference.id == ref_id)
            )
            if existing.scalar_one_or_none() is not None:
                continue
            ref = RemediationCostReference(**{k: v for k, v in ref_data.items() if v is not None or k == "is_forfait"})
            # Ensure nullable fields not in ref_data are set
            for field in (
                "forfait_min",
                "forfait_median",
                "forfait_max",
                "cost_per_m2_min",
                "cost_per_m2_median",
                "cost_per_m2_max",
            ):
                if field not in ref_data or ref_data[field] is None:
                    setattr(ref, field, None)
            session.add(ref)
        await session.commit()
        count = len(COST_REFERENCES)
        print(f"  ✓ Remediation cost references: {count} entries seeded/verified")


if __name__ == "__main__":
    asyncio.run(seed_cost_references())
