"""
SwissBuildingOS - Seed Verification

Smoke check that the seeded database has enough data for the app and e2e:real tests.
Exits 0 if OK, 1 if dataset is insufficient.

Usage:
    python -m app.seeds.seed_verify
"""

import asyncio
import sys
from dataclasses import dataclass

from sqlalchemy import func, select

from app.database import AsyncSessionLocal
from app.models.action_item import ActionItem
from app.models.building import Building
from app.models.building_snapshot import BuildingSnapshot
from app.models.building_trust_score_v2 import BuildingTrustScore
from app.models.campaign import Campaign
from app.models.change_signal import ChangeSignal
from app.models.compliance_artefact import ComplianceArtefact
from app.models.data_quality_issue import DataQualityIssue
from app.models.diagnostic import Diagnostic
from app.models.document import Document
from app.models.evidence_pack import EvidencePack
from app.models.intervention import Intervention
from app.models.post_works_state import PostWorksState
from app.models.readiness_assessment import ReadinessAssessment
from app.models.sample import Sample
from app.models.saved_simulation import SavedSimulation
from app.models.unknown_issue import UnknownIssue
from app.models.user import User

# Required checks: these must meet a minimum count or verification fails.
THRESHOLDS = {
    "users": 2,
    "buildings": 3,
    "diagnostics": 1,
    "samples": 1,
    "documents": 1,
    "campaigns": 1,
}

# Scenario-aware thresholds: verify scenario-rich buildings exist after seed_scenarios.
SCENARIO_THRESHOLDS = {
    "interventions": 1,
    "action_items": 1,
    "compliance_artefacts": 1,
    "post_works_states": 1,
    "readiness_assessments": 1,
    "building_trust_scores": 1,
}

# Core models that must meet THRESHOLDS.
CORE_MODELS = [
    ("users", User),
    ("buildings", Building),
    ("diagnostics", Diagnostic),
    ("samples", Sample),
    ("documents", Document),
    ("campaigns", Campaign),
]


@dataclass
class InfoCheck:
    """An informational check for a runtime-generated model."""

    label: str
    model: type
    note: str


# Informational checks: 0 is acceptable; these are generated at runtime.
INFO_CHECKS: list[InfoCheck] = [
    InfoCheck("saved_simulations", SavedSimulation, "generated by user"),
    InfoCheck("data_quality_issues", DataQualityIssue, "runtime-generated"),
    InfoCheck("change_signals", ChangeSignal, "runtime-generated by change_signal_generator"),
    InfoCheck(
        "readiness_assessments",
        ReadinessAssessment,
        "runtime-generated by readiness_reasoner",
    ),
    InfoCheck(
        "building_trust_scores",
        BuildingTrustScore,
        "runtime-generated by trust_score_calculator",
    ),
    InfoCheck("unknown_issues", UnknownIssue, "runtime-generated by unknown_generator"),
    InfoCheck("post_works_states", PostWorksState, "runtime-generated by post_works_service"),
    InfoCheck("compliance_artefacts", ComplianceArtefact, "created by users"),
    InfoCheck("evidence_packs", EvidencePack, "created by users"),
    InfoCheck("building_snapshots", BuildingSnapshot, "created by time machine service"),
]


async def verify() -> tuple[list[str], dict[str, int], list[str]]:
    """Return (failures, counts, info_messages).

    failures: list of threshold violations (non-empty = exit 1).
    counts: dict of label -> count for all checked models.
    info_messages: informational notes for runtime-generated models.
    """
    failures: list[str] = []
    counts: dict[str, int] = {}
    info_messages: list[str] = []

    async with AsyncSessionLocal() as session:
        # Core threshold checks
        for label, model in CORE_MODELS:
            result = await session.execute(select(func.count()).select_from(model))
            counts[label] = result.scalar() or 0

        for label, minimum in THRESHOLDS.items():
            actual = counts[label]
            if actual < minimum:
                failures.append(f"{label}: {actual} (need >= {minimum})")

        # Informational checks (runtime-generated models)
        for check in INFO_CHECKS:
            result = await session.execute(select(func.count()).select_from(check.model))
            count = result.scalar() or 0
            counts[check.label] = count
            if count == 0:
                info_messages.append(f"{check.label}: 0 records — {check.note}")
            else:
                info_messages.append(f"{check.label}: {count} records")

    return failures, counts, info_messages


async def verify_scenarios() -> tuple[list[str], dict[str, int]]:
    """Check scenario-aware thresholds (post seed_scenarios).

    Returns (warnings, counts). Warnings are non-fatal but signal missing scenario depth.
    """
    scenario_models = {
        "interventions": Intervention,
        "action_items": ActionItem,
        "compliance_artefacts": ComplianceArtefact,
        "post_works_states": PostWorksState,
        "readiness_assessments": ReadinessAssessment,
        "building_trust_scores": BuildingTrustScore,
    }
    warnings: list[str] = []
    counts: dict[str, int] = {}

    async with AsyncSessionLocal() as session:
        for label, model in scenario_models.items():
            result = await session.execute(select(func.count()).select_from(model))
            count = result.scalar() or 0
            counts[label] = count
            minimum = SCENARIO_THRESHOLDS.get(label, 0)
            if count < minimum:
                warnings.append(f"{label}: {count} (scenario expects >= {minimum})")

    return warnings, counts


async def main():
    failures, counts, info_messages = await verify()
    print("=== Seed Verification ===")

    # Print core model counts
    for label, _model in CORE_MODELS:
        print(f"  {label}: {counts[label]}")

    # Print informational checks
    if info_messages:
        print("--- Runtime-generated models ---")
        for msg in info_messages:
            print(f"  {msg}")

    if failures:
        print("FAIL — dataset insufficient:")
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)
    else:
        print("OK — dataset ready for app and e2e:real")

    # Scenario-aware checks (non-fatal)
    scenario_warnings, scenario_counts = await verify_scenarios()
    if scenario_warnings:
        print("--- Scenario depth warnings (run seed_scenarios to fix) ---")
        for w in scenario_warnings:
            print(f"  ⚠ {w}")
    else:
        print("OK — scenario depth sufficient")
        for label, count in scenario_counts.items():
            print(f"  {label}: {count}")


if __name__ == "__main__":
    asyncio.run(main())
