"""
SwissBuildingOS - Source Registry Seed
Idempotent seed for the source registry with all known data sources.

Usage:
    python -m app.seeds.seed_source_registry
"""

import asyncio
import uuid

from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models.source_registry import SourceRegistryEntry

# ---------------------------------------------------------------------------
# Stable UUIDs for idempotent upserts (source_registry namespace)
# ---------------------------------------------------------------------------
_NS = uuid.UUID("10000000-0000-4000-a000-000000000000")


def _source_id(name: str) -> uuid.UUID:
    return uuid.uuid5(_NS, name)


# ---------------------------------------------------------------------------
# Source definitions — covers families A-H from Total Source Discovery Plan
# ---------------------------------------------------------------------------
SOURCES: list[dict] = [
    # ── Family A: Identity ──────────────────────────────────────────────
    {
        "name": "geo_admin_madd",
        "display_name": "MADD / geo.admin (GWR)",
        "description": "Federal building and dwelling register. Canonical source for EGID, address, construction year.",
        "family": "identity",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/find",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 2160,  # 90 days
        "trust_posture": "canonical_identity",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "passport", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_cadastre",
        "display_name": "Cadastre / geo.admin",
        "description": "Federal cadastral survey. Canonical source for EGRID, parcel geometry.",
        "family": "identity",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 2160,
        "trust_posture": "canonical_identity",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "rdppf_federal",
        "display_name": "RDPPF / OEREB (federal)",
        "description": "Public law restrictions on land ownership. Federal extract via geo.admin.",
        "family": "identity",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://rdppf.geo.admin.ch/api/v1/full",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "safe_to_x", "passport"],
        "status": "active",
        "priority": "now",
    },
    # ── Family B: Spatial ───────────────────────────────────────────────
    {
        "name": "geo_admin_noise_road",
        "display_name": "Bruit routier (OFEV)",
        "description": "Road noise levels from FOEN via geo.admin.",
        "family": "spatial",
        "circle": 2,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 168,
        "trust_posture": "observed_context",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_noise_rail",
        "display_name": "Bruit ferroviaire (OFEV)",
        "description": "Rail noise levels from FOEN via geo.admin.",
        "family": "spatial",
        "circle": 2,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 168,
        "trust_posture": "observed_context",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_solar",
        "display_name": "Potentiel solaire (BFE)",
        "description": "Solar suitability for rooftops from SFOE via geo.admin.",
        "family": "spatial",
        "circle": 2,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 2160,
        "trust_posture": "observed_context",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_public_transport",
        "display_name": "Desserte TP (ARE)",
        "description": "Public transport quality classes from ARE via geo.admin.",
        "family": "spatial",
        "circle": 2,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 2160,
        "trust_posture": "observed_context",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_thermal_networks",
        "display_name": "Reseaux de chaleur (BFE)",
        "description": "District heating networks from SFOE via geo.admin.",
        "family": "spatial",
        "circle": 2,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 2160,
        "trust_posture": "observed_context",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home"],
        "status": "active",
        "priority": "next",
    },
    # ── Family C: Constraint ────────────────────────────────────────────
    {
        "name": "geo_admin_radon",
        "display_name": "Radon (OFSP)",
        "description": "Radon risk map from FOPH via geo.admin. Canonical for radon constraint.",
        "family": "constraint",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 168,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "safe_to_x", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_natural_hazards",
        "display_name": "Dangers naturels — crues (OFEV)",
        "description": "Flood hazard zones from FOEN via geo.admin.",
        "family": "constraint",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_groundwater",
        "display_name": "Protection eaux souterraines (OFEV)",
        "description": "Groundwater protection zones from FOEN via geo.admin.",
        "family": "constraint",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_contaminated_sites",
        "display_name": "Sites contamines (OFEV)",
        "description": "Contaminated sites registry from FOEN via geo.admin.",
        "family": "constraint",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "geo_admin_heritage_isos",
        "display_name": "Patrimoine ISOS (BAK)",
        "description": "Federal inventory of heritage sites from BAK via geo.admin.",
        "family": "constraint",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://api3.geo.admin.ch/rest/services/api/MapServer/identify",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 2160,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "safe_to_x", "passport"],
        "status": "active",
        "priority": "now",
    },
    # ── Family D: Procedure ─────────────────────────────────────────────
    {
        "name": "vd_asbestos_procedure",
        "display_name": "Procedure amiante VD (DEIS/SAT)",
        "description": "Vaud canton asbestos diagnostic and renovation procedure rules.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["VD"],
        "workspace_consumers": ["case_room", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "ge_asbestos_procedure",
        "display_name": "Procedure amiante GE (SABRA)",
        "description": "Geneva canton asbestos diagnostic and renovation procedure rules.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["GE"],
        "workspace_consumers": ["case_room", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "suva_cfst_6503",
        "display_name": "SUVA CFST 6503",
        "description": "Work categories for asbestos works (minor/medium/major). Federal directive.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["case_room", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    # ── Family E: Standard / Regulation ─────────────────────────────────
    {
        "name": "otconst_art60a",
        "display_name": "OTConst Art. 60a/82-86",
        "description": "Federal construction ordinance — asbestos renovation obligations.",
        "family": "standard",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["safe_to_x", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "orrchim_pcb_lead",
        "display_name": "ORRChim Annexe 2.15/2.18",
        "description": "Chemical risk reduction ordinance — PCB and lead thresholds.",
        "family": "standard",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["safe_to_x", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "orap_radon",
        "display_name": "ORaP Art. 110",
        "description": "Radiological protection ordinance — radon thresholds (300/1000 Bq/m3).",
        "family": "standard",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["safe_to_x", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "oled_waste",
        "display_name": "OLED (dechets)",
        "description": "Waste management ordinance — type_b/type_e/special waste classes.",
        "family": "standard",
        "circle": 1,
        "source_class": "official",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["case_room"],
        "status": "active",
        "priority": "now",
    },
    # ── Family F: Commercial ────────────────────────────────────────────
    {
        "name": "vd_public_rcb",
        "display_name": "Vaud RCB Public (ASIT)",
        "description": "Vaud public building data (adresses, batiments) from cantonal open data.",
        "family": "commercial",
        "circle": 2,
        "source_class": "observed",
        "access_mode": "bulk",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 720,
        "trust_posture": "supporting_evidence",
        "geographic_scope": "cantonal",
        "canton_scope": ["VD"],
        "workspace_consumers": ["building_home", "portfolio"],
        "status": "active",
        "priority": "now",
    },
    # ── Family G: Partner ───────────────────────────────────────────────
    {
        "name": "partner_diagnostic_lab",
        "display_name": "Laboratoires partenaires",
        "description": "Partner diagnostic laboratories providing sample analysis results.",
        "family": "partner",
        "circle": 2,
        "source_class": "partner_fed",
        "access_mode": "partner",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "supporting_evidence",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["case_room", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "partner_erp_bridge",
        "display_name": "ERP Bridge (Batiscan V4)",
        "description": "Immutable read-only bridge from Batiscan V4 ERP. No shared DB.",
        "family": "partner",
        "circle": 2,
        "source_class": "partner_fed",
        "access_mode": "partner",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "supporting_evidence",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "case_room"],
        "status": "active",
        "priority": "now",
    },
    # ── Family H: Live / Document ───────────────────────────────────────
    {
        "name": "document_upload",
        "display_name": "Documents uploades",
        "description": "User-uploaded documents (diagnostic reports, plans, certificates).",
        "family": "document",
        "circle": 3,
        "source_class": "observed",
        "access_mode": "file",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "supporting_evidence",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["building_home", "case_room", "passport"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "ai_extraction",
        "display_name": "AI Extraction (LLM)",
        "description": "LLM-based extraction from diagnostic reports. Phase 1 of AI layer.",
        "family": "live",
        "circle": 3,
        "source_class": "derived",
        "access_mode": "api",
        "freshness_policy": "event_driven",
        "cache_ttl_hours": None,
        "trust_posture": "derived_only",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["case_room"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "ai_feedback",
        "display_name": "AI Feedback Loop",
        "description": "User corrections feeding the AI rule engine. Data flywheel.",
        "family": "live",
        "circle": 3,
        "source_class": "derived",
        "access_mode": "api",
        "freshness_policy": "real_time",
        "cache_ttl_hours": None,
        "trust_posture": "derived_only",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["case_room"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "field_observation",
        "display_name": "Observations terrain",
        "description": "Field observations captured on-site by diagnosticians.",
        "family": "live",
        "circle": 3,
        "source_class": "observed",
        "access_mode": "api",
        "freshness_policy": "real_time",
        "cache_ttl_hours": None,
        "trust_posture": "supporting_evidence",
        "geographic_scope": "switzerland",
        "canton_scope": None,
        "workspace_consumers": ["case_room", "building_home"],
        "status": "active",
        "priority": "now",
    },
    # ── Family D: Procedure — Subsidy programs ─────────────────────────
    {
        "name": "subsidy_programs_vd",
        "display_name": "Subventions Programme Batiments VD",
        "description": "Vaud canton subsidy/funding programs for building renovation and pollutant remediation.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://www.vd.ch/themes/environnement/energie/subventions",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 168,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["VD"],
        "workspace_consumers": ["procedure_workspace", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "subsidy_programs_ge",
        "display_name": "Subventions Programme Batiments GE",
        "description": "Geneva canton subsidy/funding programs for building renovation and pollutant remediation.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://www.ge.ch/dossier/programme-batiments",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 168,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["GE"],
        "workspace_consumers": ["procedure_workspace", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "subsidy_programs_fr",
        "display_name": "Subventions Programme Batiments FR",
        "description": "Fribourg canton subsidy/funding programs for building renovation.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://www.fr.ch/energie",
        "freshness_policy": "monthly",
        "cache_ttl_hours": 168,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["FR"],
        "workspace_consumers": ["procedure_workspace", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    # ── Family D: Procedure — Cantonal authorities ─────────────────────
    {
        "name": "cantonal_authorities_vd",
        "display_name": "Autorites cantonales VD",
        "description": "Vaud canton authority contacts, portals, and filing requirements.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://www.vd.ch",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["VD"],
        "workspace_consumers": ["case_room", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "cantonal_authorities_ge",
        "display_name": "Autorites cantonales GE",
        "description": "Geneva canton authority contacts, portals, and filing requirements.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://www.ge.ch",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["GE"],
        "workspace_consumers": ["case_room", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
    {
        "name": "cantonal_authorities_fr",
        "display_name": "Autorites cantonales FR",
        "description": "Fribourg canton authority contacts, portals, and filing requirements.",
        "family": "procedure",
        "circle": 1,
        "source_class": "official",
        "access_mode": "api",
        "base_url": "https://www.fr.ch",
        "freshness_policy": "quarterly",
        "cache_ttl_hours": 720,
        "trust_posture": "canonical_constraint",
        "geographic_scope": "cantonal",
        "canton_scope": ["FR"],
        "workspace_consumers": ["case_room", "safe_to_x"],
        "status": "active",
        "priority": "now",
    },
]


async def seed_source_registry() -> None:
    """Seed the source registry with all known sources. Idempotent."""
    async with AsyncSessionLocal() as db:
        for source_data in SOURCES:
            source_id = _source_id(source_data["name"])
            stmt = select(SourceRegistryEntry).where(SourceRegistryEntry.name == source_data["name"])
            result = await db.execute(stmt)
            existing = result.scalar_one_or_none()

            if existing:
                # Update fields
                for key, value in source_data.items():
                    if key != "name":
                        setattr(existing, key, value)
            else:
                entry = SourceRegistryEntry(id=source_id, **source_data)
                db.add(entry)

        await db.commit()
        print(f"Source registry seeded: {len(SOURCES)} sources.")


if __name__ == "__main__":
    asyncio.run(seed_source_registry())
