from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_MD = REPO_ROOT / "docs" / "test-inventory.md"
OUTPUT_JSON = REPO_ROOT / "docs" / "test-inventory.json"


@dataclass
class TestFileStats:
    path: str
    layer: str
    lines: int
    tests: int
    describes: int
    flags: list[str]


def iter_test_files() -> Iterable[tuple[Path, str]]:
    roots = [
        (REPO_ROOT / "backend" / "tests", "backend_pytest"),
        (REPO_ROOT / "frontend" / "src" / "components" / "__tests__", "frontend_unit"),
        (REPO_ROOT / "frontend" / "e2e", "frontend_e2e_mock"),
        (REPO_ROOT / "frontend" / "e2e-real", "frontend_e2e_real"),
    ]
    for root, layer in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if "__pycache__" in path.parts or "node_modules" in path.parts:
                continue
            if layer == "backend_pytest" and not path.name.startswith("test_"):
                continue
            if layer != "backend_pytest" and not (
                path.name.endswith(".test.ts")
                or path.name.endswith(".test.tsx")
                or path.name.endswith(".spec.ts")
                or path.name.endswith(".spec.tsx")
            ):
                continue
            yield path, layer


def count_matches(pattern: str, content: str) -> int:
    return len(re.findall(pattern, content, flags=re.MULTILINE))


def classify_flags(layer: str, lines: int, tests: int) -> list[str]:
    flags: list[str] = []
    if lines >= 300:
        flags.append("oversized")
    elif lines >= 200:
        flags.append("large")
    if tests >= 16:
        flags.append("high_case_count")
    elif tests >= 10:
        flags.append("medium_case_count")
    if layer.startswith("frontend_e2e") and (lines >= 180 or tests >= 8):
        flags.append("broad_e2e")
    if layer == "backend_pytest" and lines >= 220 and tests >= 10:
        flags.append("broad_backend")
    return flags


def analyze_file(path: Path, layer: str) -> TestFileStats:
    content = path.read_text(encoding="utf-8")
    lines = len(content.splitlines())
    if layer == "backend_pytest":
        tests = count_matches(r"^\s*def\s+test_", content)
        describes = 0
    else:
        tests = count_matches(r"\b(?:it|test)\s*\(", content)
        describes = count_matches(r"\bdescribe\s*\(", content)
    flags = classify_flags(layer, lines, tests)
    return TestFileStats(
        path=str(path.relative_to(REPO_ROOT)).replace("\\", "/"),
        layer=layer,
        lines=lines,
        tests=tests,
        describes=describes,
        flags=flags,
    )


def summarize(stats: list[TestFileStats]) -> dict[str, object]:
    by_layer: dict[str, dict[str, int]] = {}
    for row in stats:
        bucket = by_layer.setdefault(
            row.layer,
            {"files": 0, "lines": 0, "tests": 0, "flagged": 0},
        )
        bucket["files"] += 1
        bucket["lines"] += row.lines
        bucket["tests"] += row.tests
        if row.flags:
            bucket["flagged"] += 1
    top_by_lines = sorted(stats, key=lambda item: (-item.lines, item.path))[:15]
    top_by_tests = sorted(stats, key=lambda item: (-item.tests, item.path))[:15]
    flagged = [row for row in stats if row.flags]
    return {
        "total_files": len(stats),
        "total_lines": sum(row.lines for row in stats),
        "total_tests": sum(row.tests for row in stats),
        "by_layer": by_layer,
        "flagged_count": len(flagged),
        "top_by_lines": [asdict(row) for row in top_by_lines],
        "top_by_tests": [asdict(row) for row in top_by_tests],
        "flagged": [asdict(row) for row in sorted(flagged, key=lambda item: (-item.lines, item.path))],
    }


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        "# Test Inventory",
        "",
        "Generated by `python scripts/test_inventory.py`.",
        "",
        f"- Total files: `{summary['total_files']}`",
        f"- Total lines: `{summary['total_lines']}`",
        f"- Total test cases (approx): `{summary['total_tests']}`",
        f"- Flagged files: `{summary['flagged_count']}`",
        "",
        "## By Layer",
        "",
        "| Layer | Files | Lines | Test cases | Flagged |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    by_layer = summary["by_layer"]
    assert isinstance(by_layer, dict)
    for layer, bucket in by_layer.items():
        lines.append(
            f"| `{layer}` | {bucket['files']} | {bucket['lines']} | {bucket['tests']} | {bucket['flagged']} |"
        )

    def add_table(title: str, rows: list[dict[str, object]]) -> None:
        lines.extend(
            [
                "",
                f"## {title}",
                "",
                "| File | Layer | Lines | Tests | Flags |",
                "| --- | --- | ---: | ---: | --- |",
            ]
        )
        for row in rows:
            flags = ", ".join(row["flags"]) if row["flags"] else "-"
            lines.append(
                f"| `{row['path']}` | `{row['layer']}` | {row['lines']} | {row['tests']} | {flags} |"
            )

    add_table("Top by Lines", summary["top_by_lines"])
    add_table("Top by Test Cases", summary["top_by_tests"])
    add_table("Flagged for Review", summary["flagged"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a lightweight inventory of repo tests.")
    parser.add_argument("--write", action="store_true", help="Write markdown and JSON reports under docs/.")
    args = parser.parse_args()

    stats = [analyze_file(path, layer) for path, layer in iter_test_files()]
    summary = summarize(stats)
    markdown = render_markdown(summary)

    if args.write:
        OUTPUT_MD.write_text(markdown, encoding="utf-8")
        OUTPUT_JSON.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        print(f"Wrote {OUTPUT_MD.relative_to(REPO_ROOT)} and {OUTPUT_JSON.relative_to(REPO_ROOT)}")
    else:
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
